# Generated by Django 5.2.2 on 2025-11-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='marketplacepost',
            name='status_idx',
        ),
        migrations.RemoveField(
            model_name='marketplacepost',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='marketplacepost',
            name='retry_count',
        ),
        migrations.RemoveField(
            model_name='marketplacepost',
            name='status',
        ),
    ]
