# Generated by Django 5.2.2 on 2025-11-03 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_encrypt_existing_passwords'),
        ('postings', '0002_remove_marketplacepost_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(blank=True, null=True)),
                ('post_title', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('created', 'Post Created'), ('posted', 'Post Posted to Facebook')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account_email', models.EmailField(max_length=254)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.facebookaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Post Analytics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'action', 'timestamp'], name='user_action_time_idx'), models.Index(fields=['user', 'timestamp'], name='user_time_idx'), models.Index(fields=['account', 'action'], name='account_action_idx'), models.Index(fields=['action', 'timestamp'], name='action_time_idx')],
            },
        ),
    ]
